---
- name: Add Elastic Repository
  yum_repository:
    file: '{{ elastic_repofile_path }}'
    name: 'elastic-7.x'
    description: 'Elastic repository for 8.x packages'
    baseurl: '{{ elastic_repo_baseurl }}'
    gpgcheck: yes
    gpgkey: '{{ elastic_repo_gpg_key_url }}'
    enabled: yes
  register: yum_repo_installed

- name: Import Elastic GPG key
  rpm_key:
    key: '{{ elastic_repo_gpg_key_url }}'
    state: present
